// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3G1g3hW1NCvtEyDLeI261TcRoAgCn9U',
    appId: '1:569087329804:web:3212b02a7b3ff0fd185029',
    messagingSenderId: '569087329804',
    projectId: 'kozo-ibaraki',
    authDomain: 'kozo-ibaraki.firebaseapp.com',
    storageBucket: 'kozo-ibaraki.firebasestorage.app',
    measurementId: 'G-9YXC26QYWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2XKZIe5Esu4fuErDeItzUbxQ-aDTgFk',
    appId: '1:569087329804:android:48a8a9c425f6aafa185029',
    messagingSenderId: '569087329804',
    projectId: 'kozo-ibaraki',
    storageBucket: 'kozo-ibaraki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUVfKsmoSAk7zZWJOVqzskotdmhaV7LnI',
    appId: '1:569087329804:ios:504d5a68563ecd95185029',
    messagingSenderId: '569087329804',
    projectId: 'kozo-ibaraki',
    storageBucket: 'kozo-ibaraki.firebasestorage.app',
    iosBundleId: 'com.example.kozoIbaraki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUVfKsmoSAk7zZWJOVqzskotdmhaV7LnI',
    appId: '1:569087329804:ios:504d5a68563ecd95185029',
    messagingSenderId: '569087329804',
    projectId: 'kozo-ibaraki',
    storageBucket: 'kozo-ibaraki.firebasestorage.app',
    iosBundleId: 'com.example.kozoIbaraki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU3G1g3hW1NCvtEyDLeI261TcRoAgCn9U',
    appId: '1:569087329804:web:ff9d7b286700f806185029',
    messagingSenderId: '569087329804',
    projectId: 'kozo-ibaraki',
    authDomain: 'kozo-ibaraki.firebaseapp.com',
    storageBucket: 'kozo-ibaraki.firebasestorage.app',
    measurementId: 'G-7Q6XN47EKD',
  );
}
